name: Build and Commit JAR

on:
  push:
    branches:
      - main  # Replace with your default branch name if different
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # Change this if your project uses a different Java version

    # Build the Maven project
    - name: Build with Maven
      run: mvn clean package

    # Add the generated JAR to a specific folder
    - name: Move JAR to Release Directory
      run: |
        mkdir -p release
        mv target/*.jar release/

    # Commit the JAR file back to the repository
    - name: Commit JAR file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add release/
        git commit -m "Add generated JAR file [CI]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
